const _ = require("lodash");
const Events = exports.Events = {
  id: "identify",
  d: "disconnect",
  1: "spawn",
  2: "playerIn",
  3: "playerUpdate",
  4: "playerOut",
  5: "lbUpdate", //leaderboard
  6: "thingCreate",
  7: "swing",
  8: "shake",
  9: "score",
  10: "healthUpdate",
  11: "death",
  12: "thingDestroy",
  13: "kill",
  14: "upgrade",
  15: "age",
  16: "weaponAvailable",
  17: "itemAvailable",
  ac: "allianceCreate",
  ad: "allianceDelete",
  an: "notif",
  st: "allianceJoin",
  sa: "allianceUpdate",
  dtv: "timeUpdate",
  IDENTIFY: "id",
  DISCONNECT: "d",
  ALLIANCE_CREATE: "ac",
  ALLIANCE_DELETE: "ad",
  NOTIF: "an",
  ALLIANCE_JOIN: "st",
  ALLIANCE_UPDATE: "sa",
  TIME_UPDATE: "dtv"
};
Object.assign(Events, _.invert(Object.assign({}, [undefined, "SPAWN", "PLAYER_IN", "PLAYER_UPDATE", "PLAYER_OUT", "LB_UPDATE", "THING_CREATE", "SWING", "SHAKE",
  "SCORE", "HEALTH_UPDATE", "DEATH", "THING_DESTROY", "KILL", "UPGRADE", "AGE", "WEAPON_AVAILABLE", "ITEM_AVAILABLE"])));